T = ["m","l","i"]
print(f"dear {T[0].title()} you are invited")
print(f"dear {T[1].title()} you are invited")
print(f"dear {T[2].title()} you are invited")
print(f"{T[0].title()} can't come")
T[0] = "mb"
print(f"dear {T[0].title()} you are invited")
print(f"dear {T[1].title()} you are invited")
print(f"dear {T[2].title()} you are invited")
T.insert(0,"dk")
T.insert(3,"y")
T.append("s")
print(f"\ndear {T[0].title()} you are invited")
print(f"dear {T[1].title()} you are invited")
print(f"dear {T[2].title()} you are invited")
print(f"dear {T[3].title()} you are invited")
print(f"dear {T[4].title()} you are invited")
print(f"dear {T[5].title()} you are invited")
print("I can bring only two sorry!")
print(f"sorry {T.pop(0).title()}")
print(f"sorry {T.pop(0).title()}")
print(f"sorry {T.pop(0).title()}")
print(f"sorry {T.pop(0).title()}")
print(f"\ndear {T[0].title()} you are invited")
print(f"dear {T[1].title()} you are invited")
del T[0]
del T[0]
print(T)
R = len(T)
print(R)